feat(search-extension-template): add types
lumapps/lumapps-extensions-templates pull request #109
Opened 2022-06-09 13:59 UTC by radiuso

Add types in Search template

2022-06-10 14:10 UTC, gregorycat requested changes

2022-06-10 15:32 UTC, radiuso commented on template-search-extension/src/widget/Search/index.ts
> +export const searchFunction = async ({ query, page, pageSize }: ExtensionInput): Promise<ExtensionOutput> => {
Oui, c'est des exemples, les devs feront ce qu'ils veulent ensuite

2022-06-13 08:12 UTC, gregorycat commented on template-search-extension/src/widget/Search/index.ts
> +export const searchFunction = async ({ query, page, pageSize }: ExtensionInput): Promise<ExtensionOutput> => {
Mais a part le connectorId, ils sont tous obligatoires, non ?

2022-06-13 11:40 UTC, radiuso commented
@gregorycat @LaurentMox j'ai fait cette PR pour externaliser les types 
https://github.com/lumapps/lumapps-sdk-js/pull/65

2022-06-14 11:57 UTC, gregorycat approved these changes
Seems good

2022-06-17 08:25 UTC, gregorycat submitted a review, later dismissed

2022-06-17 08:44 UTC, gregorycat commented
@germainruget or @LaurentMox can you merge this PR ?
Thx

2022-06-20 13:28 UTC, merged