Doc update
lumapps/lumapps-extensions-templates pull request #19
Opened 2020-10-14 12:31 UTC by aureldent

Use [docsify](https://docsify.js.org/#/quickstart ) for the doc
Add contributing.md describing
* how to bump version and publish to npm 
* how to dev the doc

2020-11-04 08:24 UTC, gregorycat requested changes

2020-11-04 08:24 UTC, gregorycat commented on CONTRIBUTING.md
> +Once merged on master you can publish it via the lumapps npm profile by going to the master branch and runnign
```suggestion
Once merged on master you can publish it via the lumapps npm profile by going to the master branch and running
```

2020-11-13 08:01 UTC, maximevast approved these changes

2020-11-17 09:55 UTC, gregorycat approved these changes

2020-11-17 10:08 UTC, merged