feat(config): update config files for extensions
lumapps/lumapps-extensions-templates pull request #21
Opened 2020-11-19 13:13 UTC by gregorycat

Update the configuration file to match the query params neede to create and/or update an extension in MP

Plus update deps in packages.json

2020-11-19 13:34 UTC, aureldent approved these changes

2020-11-19 14:26 UTC, maximevast requested changes

2020-11-19 14:48 UTC, gregorycat commented on template-react/src/config.js
>  const providerId = 'LumAppsLAB';
Yes we can

2020-11-20 13:02 UTC, maximevast approved these changes

2020-11-20 13:02 UTC, merged