update version 0.4.4
lumapps/lumapps-extensions-templates pull request #68
Opened 2021-09-23 09:00 UTC by germainruget

2021-09-23 14:10 UTC, LaurentMox requested changes

2021-09-23 14:10 UTC, LaurentMox commented on template-share-extension/package.json
> +    "lumapps-sdk-js": "^1.0.0",
This version is bugged, please use the previous one (0.0.44 as far as i remember)

2021-09-23 14:10 UTC, LaurentMox commented on template-widget-extension/package.json
> +    "lumapps-sdk-js": "^1.0.0",
This version is bugged, please use the previous one (0.0.44 as far as i remember)

2021-09-23 14:33 UTC, gregorycat approved these changes

2021-09-23 14:35 UTC, LaurentMox approved these changes
LGTM

2021-09-23 14:35 UTC, LaurentMox commented on template-widget-extension/package.json
> +    "axios": "0.21.1",
On the _web_ they updagraded to 0.21.2, can you do it too please?

2021-09-23 14:36 UTC, LaurentMox commented on template-widget-extension/package.json
> +    "axios": "0.21.1",
To 0.21.4 sorry, it's the latest patch

2021-09-24 08:05 UTC, gregorycat approved these changes

2021-09-24 08:06 UTC, LaurentMox approved these changes

2021-09-24 08:11 UTC, merged