chore(template): update packages and doc
lumapps/lumapps-extensions-templates pull request #94
Opened 2022-02-23 11:58 UTC by germainruget

Update packages : 

- sdk : 1.7.1
- playground : 1.13.0
- shipping-server : 1.5.0

Update doc : 
- Add accountType to current User
- Add useFeatureEnabled hooks

Update changelog

2022-02-24 09:52 UTC, LaurentMox commented on docs/changelog/playground/1.12.x.md
> +- **playground:** add options to enabled feature ([75a6eba](https://github.com/lumapps/lumapps-extensions-playground/commit/75a6eba592e08bd2c295590da8b5d98140862883))
As a partner i am not sure to clearly understand what was done

2022-02-24 09:52 UTC, LaurentMox commented on docs/sdk/sdk-js.md
> +                is community feature is enabled : {isCommunityAvailable ? 'Yes' : 'No'}.
Should be reworded

2022-02-24 09:59 UTC, gregorycat requested changes

2022-02-24 09:59 UTC, gregorycat commented on docs/sdk/sdk-js.md
> +export const HelloWidget: FC = () => {
It could be interesting to provide a list of feature partner can check (not all our features but some important one, I'll try to give the list)

2022-02-25 14:20 UTC, gregorycat approved these changes

2022-02-25 15:00 UTC, merged