Doc rework
lumapps/lumapps-extensions-templates pull request #98
Opened 2022-04-05 16:02 UTC by LillyJekow

Reworked the entire documentation

2022-04-26 12:48 UTC, LaurentMox commented
@LillyJekow Can you please rebase on master?

2022-04-27 14:05 UTC, germainruget approved these changes
This looks good to me, it looks way more clear than what we had before

2022-05-16 12:11 UTC, gregorycat requested changes

2022-05-16 12:11 UTC, gregorycat commented on docs/partner/index.md
> +-   Create your private GitHub repository dedicated your marketplace extensions.
With the new Developer portal this part has been removed, we do not create a GitHub repository anymore

2022-05-16 12:11 UTC, gregorycat commented on docs/partner/index.md
> +>**Note:** You will be able to add more developers later on.
Same here, no more GitHub with the developer portal

2022-05-18 14:04 UTC, germainruget approved these changes

2022-05-18 14:18 UTC, germainruget approved these changes

2022-05-18 14:19 UTC, merged